services:
  # Backend Service
  - type: web
    name: price-pulse-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        value: dpg-db28p8uk1f9s739iapng-a
      - key: DB_NAME
        value: pricepulse_305q
      - key: DB_USER
        value: pricepulse
      - key: DB_PASSWORD
        fromDatabase:
          name: price-pulse-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: PRICEPULSE_SCHEDULER_INTERVAL_MS
        value: 1800000

  # Frontend Service
  - type: web
    name: price-pulse-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile.render
    plan: free
    buildContext: ./frontend
    envVars:
      - key: VITE_API_BASE
        value: https://price-pulse-backend-xais.onrender.com

databases:
  # PostgreSQL Database
  - name: price-pulse-db
    databaseName: pricepulse
    user: pricepulse
    plan: free
