package com.pricepulse.auth.service;

import com.pricepulse.auth.dto.AuthResponse;
import com.pricepulse.auth.dto.LoginRequest;
import com.pricepulse.auth.dto.RegisterRequest;
import com.pricepulse.auth.entity.User;
import com.pricepulse.auth.exception.AuthenticationException;
import com.pricepulse.auth.exception.RateLimitException;
import com.pricepulse.auth.repository.UserRepository;
import com.pricepulse.common.exception.ConflictException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Business logic for user registration and login.
 *
 * <p>Security invariants enforced here:
 * <ul>
 *   <li>Plaintext passwords are never stored or logged (Req 1.5).</li>
 *   <li>Login failure messages never disclose whether the email or password was wrong (Req 2.2, 2.3).</li>
 *   <li>Rate limiting blocks excessive login attempts per IP (Req 2.5).</li>
 * </ul>
 */
@Service
@Transactional
public class AuthService {

    private static final String INVALID_CREDENTIALS = "Invalid credentials";

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtService jwtService;
    private final LoginRateLimiter rateLimiter;

    public AuthService(UserRepository userRepository,
                       PasswordEncoder passwordEncoder,
                       JwtService jwtService,
                       LoginRateLimiter rateLimiter) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtService = jwtService;
        this.rateLimiter = rateLimiter;
    }

    /**
     * Register a new user.
     *
     * <p>The caller is expected to have already validated the request with {@code @Valid}.
     * This method only performs the business-level duplicate-email check.
     *
     * @param req validated registration request
     * @return the persisted {@link User} entity (without the plaintext password)
     * @throws ConflictException if a user with the given email already exists (→ 409)
     */
    public User saveUser(User user) {
        return userRepository.save(user);
    }

    public User register(RegisterRequest req) {
        if (userRepository.findByEmail(req.email()).isPresent()) {
            throw new ConflictException("Email already in use");
        }

        User user = new User();
        user.setEmail(req.email());
        // BCrypt hashes the password — the plaintext is never stored (Req 1.5)
        user.setPasswordHash(passwordEncoder.encode(req.password()));

        return userRepository.save(user);
    }

    /**
     * Authenticate a user and return an {@link AuthResponse} containing the userId and email.
     * The JWT token itself is generated by the controller so it can be placed in the cookie.
     *
     * @param req      validated login request
     * @param clientIp the originating client IP (used for rate limiting)
     * @return the authenticated {@link User} on success
     * @throws RateLimitException      if the IP is currently blocked (→ 429)
     * @throws AuthenticationException if email not found or password doesn't match (→ 401)
     */
    public User login(LoginRequest req, String clientIp) {
        if (rateLimiter.isBlocked(clientIp)) {
            throw new RateLimitException(
                    "Too many failed login attempts. Please try again later.");
        }

        // Deliberately use the same message for "user not found" and "wrong password"
        // so the response does not reveal which field was wrong (Req 2.2, 2.3).
        User user = userRepository.findByEmail(req.email()).orElseGet(() -> {
            rateLimiter.recordFailure(clientIp);
            throw new AuthenticationException(INVALID_CREDENTIALS);
        });

        if (!passwordEncoder.matches(req.password(), user.getPasswordHash())) {
            rateLimiter.recordFailure(clientIp);
            throw new AuthenticationException(INVALID_CREDENTIALS);
        }

        rateLimiter.resetFailures(clientIp);
        return user;
    }
}
